### ISSUE TITLE
自荐几个开源库

### ISSUE THREAD

**Issue by xixilive** [justjavac/awesome-wechat-weapp#106]
更易用的微信小程序API [xixilive/weapp](https://github.com/xixilive/weapp)

微信小程序Redux集成 [xixilive/redux-weapp](https://github.com/xixilive/redux-weapp)

微信小程序Login的Express中间件 [xixilive/express-weapp-auth](https://github.com/xixilive/express-weapp-auth)

**Comment by justjavac** [comment]
直接 pr 吧
