### ISSUE TITLE
自荐一下自己的小程序canvas动画库

### ISSUE THREAD

**Issue by bobiscool** [justjavac/awesome-wechat-weapp#137]
wxDraw: https://github.com/bobiscool/wxDraw

- **简单** 不需要你会canvas,会用jQuery就会使用wxDraw。
- **灵活**  所有图形，随时随地都可以进行属性修改、图形添加以及图形销毁。
- **事件支持** 小程序支持的事件只要是合理的都支持。
- **缓动动画支持** wxDraw支持链式调用动画『就像jQuery的animate一样』，并且支持几乎所有的缓动函数

demo
![google](https://user-images.githubusercontent.com/9073321/32225357-e5a1253a-be12-11e7-896d-0c8bbb828daa.gif)

**Comment by justjavac** [comment]
pr 吧
