### ISSUE TITLE
【推荐】Taro 类 react 跨端开发框架

### ISSUE THREAD

**Issue by phobal** [justjavac/awesome-wechat-weapp#176]
京东多端统一开发框架，支持用 React 的开发方式编写一次代码，生成能运行在微信小程序、H5、React Native 等的应用

https://github.com/NervJS/taro

**Comment by fanshi69** [comment]
phobal <notifications@github.com> 于 2018年6月7日周四 23:32写道：

**Comment by justjavac** [comment]
pr 吧
