### ISSUE TITLE
推荐一个wePY的IntelliJ插件

### ISSUE THREAD

**Issue by iniself** [justjavac/awesome-wechat-weapp#182]
[wePY Plugin For IntelliJ Platform](http://wepy.iniself.com/)

* 本插件适合 PhpStorm/WebStorm ，专为小程序的 WePY 框架设计
* 支持新建三种类型的wepy文件：App/Page/Component
* 支持 @ / ` / ~ 键唤醒官方/自定义组件属性、标签值的绑定完成和相关验证
* 支持行内表达式，并识别表达式中的变量
* 用liveTemplate覆盖小程序所有API的提示和自动完成
* 其他更多详见http://wepy.iniself.com

**Comment by justjavac** [comment]
pr吧
