### ISSUE TITLE
【推荐】小程序评论组件WxComment，无需其他另外的个人或者云服务器，直接集成

### ISSUE THREAD

**Issue by XiaoBaiAI** [justjavac/awesome-wechat-weapp#186]
🏷️WxComment ([https://github.com/yicm/WxComment](https://github.com/yicm/WxComment) )是一个微信小程序(Mini Program of WeChat)的评论插件，结合BaaS提供商https://leancloud.cn ，无需其他另外的个人或者云服务器，就可以免费使用。解决了需要个人去注册域名、备案、购买云服务器的繁杂问题。适用于个人博客或者个人小程序需要评论、点赞、阅读量统计的用户。📑

**Comment by justjavac** [comment]
pr 吧
