### ISSUE TITLE
appId 是必须的？

### ISSUE THREAD

**Issue by WXiaoming** [justjavac/awesome-wechat-weapp#4]
创建应用的时候选择了 「没有 appId」 ，项目创建后获得一个 appId: `touristappid`，目前官网 quickstart 都跑不起

运行截图如下：

![2016-09-24 11 13 09](https://cloud.githubusercontent.com/assets/8141958/18805735/0918b800-8248-11e6-9181-552878b58f14.png)

微信开发者工具版本：v.09.092300
平台：Mac OSX 

有人能跑起来吗？

**Comment by MAYDAY1993** [comment]
创建的时候随便填了个appid  跑的起来 没问题

**Comment by galenyuan** [comment]
@WXiaoming 有开代理的话在设置中选上“不使用任何代理”

**Comment by vipzrx** [comment]
@galenyuan 微信官方开发者工具提供代理设置，为了做什么用？ 可能用到的场景有哪些？
