### ISSUE TITLE
推荐一个小程序开发问答社区，可添加

### ISSUE THREAD

**Issue by raymondyan** [justjavac/awesome-wechat-weapp#81]
https://www.weiapp.online/ 

小程序在线论坛

**Comment by Tyxiaomi** [comment]
有没有官方的人在啊？不知道怎么用这个Github。。。提问都不知道。。

**Comment by Tyxiaomi** [comment]
有没有官方的人在啊？不知道怎么用这个Github。。。提问都不知道。。

**Comment by justjavac** [comment]
@Tyxiaomi 你够了

**Comment by vipzrx** [comment]
@raymondyan  Server not found 
这个论坛已经跑路了

**Comment by raymondyan** [comment]
哈哈哈哈哈 是的
